---
env:
  global:
    - JRUBY_OPTS='-J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-Xss2m -Xcompile.invokedynamic=false'
    - BUNDLER_VERSION='2.1.4'

stages:
  - name: test
    if: branch = master AND (tag IS blank)
  - name: publish
    if: branch = master AND type = push

rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - jruby-9.2.11.1

jdk: openjdk8

before_install: gem install bundler -v $BUNDLER_VERSION

jobs:
  include:
    - stage: publish
      name: "Publish to RubyGems"
      language: ruby
      rvm: 2.7.0
      before_install: gem install bundler -v $BUNDLER_VERSION
      script: bundle exec rake -T
